#   gem install pg
development:
  adapter: postgresql
  encoding: utf8
  database: bonsai_dev
  username: demo
  password: demo123
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: bonsai_test
  username: demo
  password: demo123
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: bonsai_dev
  username: demo
  password: demo123
  host: localhost
  pool: 5
