 #Rails.application.secrets
production:
  secret_key_base: f0447e2772fb80e53c1e638f0ccce09c5bbae367fd94314d665978852dfd7fd622f708cd302bf72c99456d0b5a2ad0fb4db1e10665a37f7a94e7b88383a87814

  pepper: FwZpz3kZg/AmE9/Qy7wRo5NSOV9uF3DSkvU49lZ1Xzg=
  secret_token: Agvk2aYfA7EZgqINfSOkjsIFmXzJLJLlRfp/C9gVa6pWfJ2B/VfkBG2aWzuJdgrD0dDrivHUM0SnVlMjuHyMJ0hYHiIBdJueA6SCl7wPD7aBL/iZDIqD8HDtRUMTJPBacmVvM2YpXuG1Ctd9pqYW8UQY/5qUBRMOKCaGWm6b8Kw=
  mandrill_api_key: mandrill_api_token
  app_name: bonsaiERP
  domain: bonsaierp.com
  http_protocol: http
  s3_bucket_name: bonsaierp
  s3_access_key_id: secret_s3
  s3_secret_access_key: secret_s3_a_key
  url_scheme: 'https'

development:
  secret_key_base:  f0447e2772fb80e53c1e638f0ccce09c5bbae367fd94314d665978852dfd7fd622f708cd302bf72c99456d0b5a2ad0fb4db1e10665a37f7a94e7b88383a87814

  pepper: FwZpz3kZg/AmE9/Qy7wRo5NSOV9uF3DSkvU49lZ1Xzg=
  secret_token: Agvk2aYfA7EZgqINfSOkjsIFmXzJLJLlRfp/C9gVa6pWfJ2B/VfkBG2aWzuJdgrD0dDrivHUM0SnVlMjuHyMJ0hYHiIBdJueA6SCl7wPD7aBL/iZDIqD8HDtRUMTJPBacmVvM2YpXuG1Ctd9pqYW8UQY/5qUBRMOKCaGWm6b8Kw=
  mandrill_api_key: mandrill_api_token
  app_name: bonsaiERP
  domain: bonsaierp.com
  http_protocol: http
  s3_bucket_name: bonsaierp
  s3_access_key_id: secret_s3
  s3_secret_access_key: secret_s3_a_key
  url_scheme: 'https'

test:
  secret_key_base: f0447e2772fb80e53c1e638f0ccce09c5bbae367fd94314d665978852dfd7fd622f708cd302bf72c99456d0b5a2ad0fb4db1e10665a37f7a94e7b88383a87814

  pepper: FwZpz3kZg/AmE9/Qy7wRo5NSOV9uF3DSkvU49lZ1Xzg=
  secret_token: Agvk2aYfA7EZgqINfSOkjsIFmXzJLJLlRfp/C9gVa6pWfJ2B/VfkBG2aWzuJdgrD0dDrivHUM0SnVlMjuHyMJ0hYHiIBdJueA6SCl7wPD7aBL/iZDIqD8HDtRUMTJPBacmVvM2YpXuG1Ctd9pqYW8UQY/5qUBRMOKCaGWm6b8Kw=
  mandrill_api_key: mandrill_api_token
  app_name: bonsaiERP
  domain: bonsaierp.com
  http_protocol: http
  s3_bucket_name: bonsaierp
  s3_access_key_id: secret_s3
  s3_secret_access_key: secret_s3_a_key
  url_scheme: 'https'
